"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $username\
# $hostname\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $git_branch\
# $git_commit\
# $git_metrics\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $cobol\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $jobs\
# $battery\
# $time\
# $status\
# $shell\
# $character\
# """

format = """
[\uE0B6](fg:#af87d7)[$directory](bg:#af87d7)[\uE0B0](fg:#af87d7 bg:#5faf5f)$git_branch[\uE0B0](fg:#5faf5f bg:#afd700)$git_status[\uE0B0](#afd700 bg:#5f8787)$time[\uE0B0](fg:#5f8787 bg:#d7875f)$bun$c$cmake$dotnet$elixer$erlang$gleam$golang$java$julia$kotlin$lua$nim$nodejs$ocaml$odin$perl$php$python$rlang$ruby$rust$scala$swift$zig[\uE0B0](fg:#d7875f bg:#1c1c1c)
$character """

add_newline = true

[directory]
style = "bg:#af87d7 fg:#1c1c1c"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#5faf5f fg:#1c1c1c"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#afd700 fg:#1c1c1c"

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:#5f8787 fg:#1c1c1c"

[bun]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[c]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[cmake]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[dotnet]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[erlang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[gleam]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[golang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[java]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[julia]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[kotlin]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[lua]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[nim]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[nodejs]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[ocaml]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[odin]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[perl]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[php]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[python]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[rlang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[ruby]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[rust]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[scala]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[swift]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[zig]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d7875f fg:#1c1c1c"

[character]
success_symbol = '[➜ ](bold green)'

