"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $username\
# $hostname\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $git_branch\
# $git_commit\
# $git_metrics\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $cobol\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $jobs\
# $battery\
# $time\
# $status\
# $shell\
# $character\
# """

format = """
$os[\uE0B0](fg:#458588 bg:#b16286)[ $directory](bg:#b16286)[\uE0B0](fg:#b16286 bg:#689d6a)$git_branch[\uE0B0](fg:#689d6a bg:#98971a)$git_status[\uE0B0](#98971a bg:#458588)$time[\uE0B0](fg:#458588 bg:#d65d0e)$bun$c$cmake$dotnet$elixer$erlang$gleam$golang$java$julia$kotlin$lua$nim$nodejs$ocaml$odin$perl$php$python$rlang$ruby$rust$scala$swift$zig[\uE0B0](fg:#d65d0e bg:#2828)
$character """

add_newline = true
[os]
format = "[ $symbol]($style)"
disabled = false
style = "bg:#458588 fg:#282828"

[os.symbols]
Pop = " "
Macos = " "

[directory]
style = "bg:#b16286 fg:#282828"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:#689d6a fg:#282828"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#98971a fg:#282828"

[time]
disabled = false
format = "[ $time ]($style)"
style = "bg:#458588 fg:#282828"

[bun]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#282828"

[c]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[cmake]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[dotnet]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[erlang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[gleam]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[golang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[java]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[julia]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[kotlin]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[lua]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[nim]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[nodejs]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[ocaml]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[odin]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[perl]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[php]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[python]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[rlang]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[ruby]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[rust]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[scala]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[swift]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[zig]
format = "[ via $symbol($version) ]($style)"
style = "bg:#d65d0e fg:#1c1c1c"

[character]
success_symbol = '[➜ ](bold green)'

